#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager

# JupyterLab git extension
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

# Github extension
# not compatible with version of jupyterlab jupyter labextension install @jupyterlab/github
