#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager

# JupyterLab Git extension
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
