# Derived from https://github.com/marketplace/actions/setup-miniconda

on: [push, pull_request]

jobs:
  test-conda:
    name: conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # A few rules to tell us the basic status
      - run: pip list
      # Actually install the environment
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      # List installed versions
      - run: pip list
      - run: pip freeze
      # Test
      - name: Test packages
        run: bash test.sh
